/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Myprojects model module.
 * @module model/Myprojects
 * @version 1.0.0
 */
class Myprojects {
    /**
     * Constructs a new <code>Myprojects</code>.
     * @alias module:model/Myprojects
     */
    constructor() { 
        
        Myprojects.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Myprojects</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Myprojects} obj Optional instance to populate.
     * @return {module:model/Myprojects} The populated <code>Myprojects</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Myprojects();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Myprojects.prototype['_id'] = undefined;






export default Myprojects;

